# Site settings
title: Connor Yako
author: "Connor Yako"
email: clyej3@gmail.com
description: Mechanical engineering researcher focused on non-anthropomorphic robotic in-hand manipulation. Also an avid Lego designer and educator.
minimal_mistakes_skin: contrast
search: false
baseurl: ""
url: "https://clyako.github.io"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

sass:
  sass_dir: _sass
  style: compressed

footer_scripts:
  - /assets/js/custom.js

collections:
  pages:
    output: true
    permalink: /:title/
  projects:
    output: true
    permalink: /projects/:path/

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: false
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: default
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "docs"
